export enum Event {
  CONNECT = 'connect',
  DISCONNECT = 'disconnect',
  EV_ENTRY = 'event_entry',
  EV_EMPLOYEE_PER_DAY = 'event_employee_per_day',
  EV_GUEST_PER_DAY = 'event_guest_per_day',
  EV_CAR_PER_DAY = 'event_car_per_day',
  EV_EXIT = 'event_exit',
  EV_EMPLOYEE = 'event_employee',
  EV_EMPLOYEEUC = 'event_employeeuc',
  EV_REAL_ON_TERRITORY_AC = 'event_real_on_territory_ac',
  EV_REAL_ON_TERRITORY_AS = 'event_real_on_territory_as',
  EV_REAL_CAR_ON_TERRITORY = 'event_real_car_on_territory',
  EV_SERVER_ROOM_SENSOR = 'event_server_room_sensor',
  EV_PROVIDER_VALUE = 'event_provider_value',
  EV_SERVER_ROOM_1_EMPLOYEE = 'event_server_room_1_employee',
  EV_SERVER_ROOM_2_EMPLOYEE = 'event_server_room_2_employee',
  EV_UPS_VALUE = 'event_ups_value',
  EV_SWITCH_VALUE = 'event_switch_value',
  EV_ROUTER_VALUE = 'event_router_value',
  EV_VMWARE_VALUE = 'event_vmware_value',
  EV_SERVER_VALUE = 'event_server_value',
}
